modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "another_furniture"
version = "${version}"
displayName = "Another Furniture"
authors = "Starfish Studios, Crispytwig, Synthestra"
description = '''
Decorating your home just got better! Another Furniture adds various furniture, with the goal of staying vanilla-styled and consistently sized, keeping normal blocks and player sizes in mind.
'''
logoFile = "icon.png"

[[dependencies.another_furniture]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.another_furniture]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "another_furniture.mixins.json"

[[mixins]]
config = "another_furniture.common.mixins.json"